/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Poppins", "sans-serif"],
      },
      colors: {
        "on-tertiary-container": "#eef0ff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#131b2e",
        "primary-container": "#2563eb",
        "on-primary-fixed-variant": "#003ea8",
        "surface-tint": "#0053db",
        "on-background": "#191c1e",
        "surface": "#f7f9fb",
        "on-surface-variant": "#434655",
        "outline": "#737686",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#54647a",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-primary-container": "#eeefff",
        "inverse-surface": "#2d3133",
        "secondary-container": "#d0e1fb",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-dim": "#d8dadc",
        "surface-container": "#eceef0",
        "secondary": "#505f76",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#656d84",
        "background": "#f7f9fb",
        "on-primary-fixed": "#00174b",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c6d7",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#eff1f3",
        "tertiary": "#4d556b",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed-variant": "#38485d",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "primary": "#004ac6",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "4px",
        "container-padding": "24px",
        "sm": "8px",
        "md": "16px",
        "base": "4px",
        "gutter": "16px",
        "lg": "24px",
        "xl": "32px"
      }
    },
  },
  plugins: [],
}
